name: chat_social
description: "Project for social chat application. Created by Laurentiu"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  window_size: ^0.1.0
  web_socket_channel: ^2.4.0
  google_sign_in: ^6.2.1
  emoji_picker_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/icon.png
  uses-material-design: true
